### ISSUE TITLE
Version 1.4.0 not working on Sublime Text 2.0.2

### ISSUE THREAD

**Issue by RomuloOliveira** [dreadatour/Flake8Lint#64]
After 1.4.0 update, Python Flake 8 Lint stopped working. It automatically updated with Package Control. Reinstalling didn't worked. I restored manually to 1.3.0 and it is working now.

I'm using Ubuntu 14.04.1 LTS.

**Comment by dreadatour** [comment]
Hi!
Sorry for that :(
Could you, please, turn on "debug" option to "true" and provide me plugin output?

**Comment by RomuloOliveira** [comment]
```
Reloading plugin /home/romulooliveira/.config/sublime-text-2/Packages/Python Flake8 Lint/Flake8Lint.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./Flake8Lint.py", line 92, in <module>
    plugin_loaded()
  File "./Flake8Lint.py", line 72, in plugin_loaded
    update_color_scheme(settings)
  File "./color_theme.py", line 170, in update_color_scheme
    sublime.set_timeout_async(generate_color_scheme_async, 0)
AttributeError: 'module' object has no attribute 'set_timeout_async'
```

I fixed with `if int(sublime.version()) >= 3000` and I got the following error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./Flake8Lint.py", line 92, in <module>
    plugin_loaded()
  File "./Flake8Lint.py", line 78, in plugin_loaded
    view = sublime.active_window().active_view()
AttributeError: 'NoneType' object has no attribute 'active_view'
```

I also fixed it and now I got:

```
Traceback (most recent call last):
  File "./color_theme.py", line 111, in generate_color_scheme_async
AttributeError: 'module' object has no attribute 'load_resource'
```

Sorry, but I think you haven't tested it on Sublime Text 2.

**Comment by krisztianfekete** [comment]
The same happened for me as well.

**Comment by dreadatour** [comment]
Sorry! Bugfix will be ready in few hours :)

**Comment by dreadatour** [comment]
Fixed. Must be fine now.

**Comment by RomuloOliveira** [comment]
It's working now, but no colors in highlight.

![image](https://cloud.githubusercontent.com/assets/3009157/5761393/5323fb84-9cc2-11e4-8cd7-d0b8923797a5.png)

These are the highlight settings:
```
"highlight_color_critical": "#981600",
"highlight_color_error": "#DA2000",
"highlight_color_warning": "#EDBA00",
```

**Comment by dreadatour** [comment]
Yes, you're right, something goes wrong with color shemes in ST2.
I'll fix this later, thank you for bug report!

**Comment by RomuloOliveira** [comment]
Thank you!

**Comment by dreadatour** [comment]
Everything should work now.

**Comment by krisztianfekete** [comment]
Thank you, this fix was very quick!

Also thank you for the plugin, this is really awesome and must to have for Python work!

**Comment by RomuloOliveira** [comment]
Colors still not working for me :(

```
Traceback (most recent call last):
  File "./color_theme.py", line 120, in generate_color_scheme_async
  File ".\xml\etree\ElementTree.py", line 962, in XML
  File ".\xml\etree\ElementTree.py", line 1118, in __init__
ImportError: No module named expat; use SimpleXMLTreeBuilder instead
```

**Comment by dreadatour** [comment]
Could you, please, show me an output of this command in ST console?
```
>>> import sublime; sublime.version()
'3065'
```

**Comment by RomuloOliveira** [comment]
```
>>> import sublime; sublime.version()
u'2221'
```

**Comment by dreadatour** [comment]
One more command, please?
```
>>> import sys; sys.version; sys.path
'2.6.9 (unknown, Sep  9 2014, 15:05:12) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]'
['./contrib', './contrib', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python26.zip', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload', '/Library/Python/2.6/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/PyObjC', '.']
```

**Comment by krisztianfekete** [comment]
I have the same output about `expat` vs `SimpleXMLTreeBuilder`, so here is my output:

```python
>>> import sys; sys.version; sys.path
'2.6.6 (r266:84292, Jun 16 2011, 22:27:44) \n[GCC 4.4.5]'
['./contrib', './contrib', '/home/kr/.config/sublime-text-2/Packages/ssl-linux/st2_linux_x64/libssl-1.0.0', '/home/kr/.config/sublime-text-2/Packages/ssl-linux/st2_linux', '/opt/Sublime Text 2.0.2/lib/python26.zip', '/opt/Sublime Text 2.0.2/lib/python2.6', '/opt/Sublime Text 2.0.2/lib/python2.6/plat-linux2', '/opt/Sublime Text 2.0.2/lib/python2.6/lib-tk', '/opt/Sublime Text 2.0.2/lib/python2.6/lib-old', '/opt/Sublime Text 2.0.2/lib/python2.6/lib-dynload', '.', '/home/kr/.config/sublime-text-2/Packages/bz2/st2_linux_x64']```

**Comment by dreadatour** [comment]
@krisztianfekete thank you! Working on it.

**Comment by RomuloOliveira** [comment]
I have the same output that @krisztianfekete 

```
import sys; sys.version; sys.path
'2.6.6 (r266:84292, Jun 16 2011, 22:27:44) \n[GCC 4.4.5]'
['./contrib', './contrib', '/home/romulooliveira/.config/sublime-text-2/Packages/ssl-linux/st2_linux_x64/libssl-1.0.0', '/home/romulooliveira/.config/sublime-text-2/Packages/ssl-linux/st2_linux', '/opt/SublimeText2/lib/python26.zip', '/opt/SublimeText2/lib/python2.6', '/opt/SublimeText2/lib/python2.6/plat-linux2', '/opt/SublimeText2/lib/python2.6/lib-tk', '/opt/SublimeText2/lib/python2.6/lib-old', '/opt/SublimeText2/lib/python2.6/lib-dynload', '.', '/home/romulooliveira/.config/sublime-text-2/Packages/bz2/st2_linux_x64']
```

**Comment by dreadatour** [comment]
Could you, please, try this branch? https://github.com/dreadatour/Flake8Lint/tree/elementtree
I have no Linux machine and can't reproduce this bug. Another option is stop to support ST2.

**Comment by dreadatour** [comment]
Plugin should use default ("invalid.deprecated") color to highlight errors if plugin color scheme was not loaded. This let use plugin until I will fix problem with XMLTreeBuilder.

**Comment by RomuloOliveira** [comment]
I found that this is not a Flake8Lint specific, but a SublimeText2 issue

http://www.sublimetext.com/forum/viewtopic.php?f=3&t=8502&p=35066&hilit=expat#p35066
http://www.sublimetext.com/forum/viewtopic.php?f=3&t=3436&p=18206&hilit=expat#p18206

They all have fixed with a `sys.path.append("/usr/lib/python2.6/lib-dynload/")`, which is already on python path, but doesn't exists on my computer. I won't install Python 2.6 to fix this issue, and I think other users won't too (it is not even available on Ubuntu packages).

Also fallback colors works well for me. Unfortunately, I think it will cause future bug reports of users who can't make colors scheme work.

I'm trying another options to make them work, hope I can get it and hope Flake8Link doesn't stop ST2

**Comment by dreadatour** [comment]
@RomuloOliveira thank you for your investigation. This is impressive! :)

Anyway, I don't think external dependency for plugin is a good idea. It should work out of the box.

If it is possible, could you, please, try this branch? https://github.com/dreadatour/Flake8Lint/tree/elementtree
Right now I have no computer with Linux installed, but my modest conclusions tells me it could works.

**Comment by RomuloOliveira** [comment]
Sorry, I just forget to try it!

Well, I tried it and at first it didn't worker, with the same error:
```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./color_theme.py", line 20, in <module>
    from elementtree import SimpleXMLTreeBuilder
ImportError: No module named elementtree
```

But then I fixed the `elementtree` path insert and it is completely working now!

Here's the diff/patch:
```diff
From 495c9ce2e4eb245d52cee57a93045fc70c27c410 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?R=C3=B4mulo=20Oliveira?= <romulo.ac.oliveira@gmail.com>
Date: Sat, 17 Jan 2015 23:04:12 -0200
Subject: [PATCH] Fix elementtree path import #64

`generate_color_scheme_async` and highlight colors are  working now
---
 color_theme.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/color_theme.py b/color_theme.py
index 4a8bf2f..f85ad77 100644
--- a/color_theme.py
+++ b/color_theme.py
@@ -16,7 +16,7 @@ from xml.etree import ElementTree
 try:
     from xml.parsers import expat  # noqa
 except ImportError:
-    sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'contrib'))
+    sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'contrib/elementtree'))
     from elementtree import SimpleXMLTreeBuilder
     ElementTree.XMLTreeBuilder = SimpleXMLTreeBuilder.TreeBuilder
 
-- 
1.9.1


```

**Comment by dreadatour** [comment]
Oh, my bad!! I am so oblivious!
In my opinion my fix is a little bit more correct, could you, please, try it? And thank you for your patience :)

**Comment by RomuloOliveira** [comment]
Yes, I agree with you. Also, works like a charm :)

Thank you so much!

@krisztianfekete: it works for you too?

**Comment by dreadatour** [comment]
You're absolutely right. Thank you again!
Fix moved to master branch (no merge, bad commit was in previous branch :).
Everything should works now.

**Comment by krisztianfekete** [comment]
Sorry for late reply, somehow I might have accidentally muted this ticket (?) - did not get notifications after a while, but yes the now released version 1.5.3 indeed works without errors on the console - and marking problems in code.
Thank you!
